<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="2" total="6" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="MySuite01" duration-ms="92" started-at="2019-05-20T15:36:13Z" finished-at="2019-05-20T15:36:13Z">
    <groups>
      <group name="fast">
        <method signature="App2Test.checker06Test()[pri:0, instance:org.andestech.learning.rfb19.g4.App2Test@3aa9e816]" name="checker06Test" class="org.andestech.learning.rfb19.g4.App2Test"/>
        <method signature="AppTest.checker01Test()[pri:-1, instance:org.andestech.learning.rfb19.g4.AppTest@17d99928]" name="checker01Test" class="org.andestech.learning.rfb19.g4.AppTest"/>
      </group> <!-- fast -->
    </groups>
    <test name="Test01" duration-ms="32" started-at="2019-05-20T15:36:13Z" finished-at="2019-05-20T15:36:13Z">
      <class name="org.andestech.learning.rfb19.g4.App3Test">
        <test-method status="PASS" signature="checker05Test()[pri:0, instance:org.andestech.learning.rfb19.g4.App3Test@18e8568]" name="checker05Test" duration-ms="11" started-at="2019-05-20T15:36:13Z" finished-at="2019-05-20T15:36:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checker05Test -->
      </class> <!-- org.andestech.learning.rfb19.g4.App3Test -->
    </test> <!-- Test01 -->
    <test name="Test02" duration-ms="8" started-at="2019-05-20T15:36:13Z" finished-at="2019-05-20T15:36:13Z">
      <class name="org.andestech.learning.rfb19.g4.App2Test">
        <test-method status="FAIL" signature="checker06Test()[pri:0, instance:org.andestech.learning.rfb19.g4.App2Test@3aa9e816]" name="checker06Test" duration-ms="0" started-at="2019-05-20T15:36:13Z" finished-at="2019-05-20T15:36:13Z">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
at org.andestech.learning.rfb19.g4.App2Test.checker06Test(App2Test.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.TestNG.privateMain(TestNG.java:1354)
at org.testng.TestNG.main(TestNG.java:1323)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checker06Test -->
      </class> <!-- org.andestech.learning.rfb19.g4.App2Test -->
      <class name="org.andestech.learning.rfb19.g4.AppTest">
        <test-method status="PASS" signature="checker01Test()[pri:-1, instance:org.andestech.learning.rfb19.g4.AppTest@17d99928]" name="checker01Test" duration-ms="1" started-at="2019-05-20T15:36:13Z" finished-at="2019-05-20T15:36:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checker01Test -->
        <test-method status="FAIL" signature="checker02Test()[pri:0, instance:org.andestech.learning.rfb19.g4.AppTest@17d99928]" name="checker02Test" duration-ms="2" started-at="2019-05-20T15:36:13Z" finished-at="2019-05-20T15:36:13Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at org.andestech.learning.rfb19.g4.AppTest.checker02Test(AppTest.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.TestNG.privateMain(TestNG.java:1354)
at org.testng.TestNG.main(TestNG.java:1323)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checker02Test -->
      </class> <!-- org.andestech.learning.rfb19.g4.AppTest -->
    </test> <!-- Test02 -->
  </suite> <!-- MySuite01 -->
</testng-results>
